name: deploy-infra

on:
  push:
    branches:
      - develop

  workflow_dispatch:
    inputs:
      action:
        description: "Choose action"
        required: true
        default: deploy
        type: choice
        options:
          - deploy
          - destroy

concurrency:
  group: infra-cardops
  cancel-in-progress: false

jobs:
  deploy:
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_dispatch' && inputs.action == 'deploy')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upgrade Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Deploy Infrastructure
        run: pwsh ./deploy.ps1

  destroy:
    if: github.event_name == 'workflow_dispatch' && inputs.action == 'destroy'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Destroy Infrastructure
        run: pwsh ./destroy.ps1
